name: Deploy Sphinx documentation to Pages

# Runs on pushes targeting the default branch
on:
  push:
    branches: [main]

# Cancel any in-progress job or run
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: deps.yml
          environment-name: multibody-book
          cache-environment: true
          cache-downloads: true

      - name: Initialize Conda
        run: echo ". $CONDA/bin/activate" >> $GITHUB_ENV

      - name: Activate Conda environment
      
      - id: deployment
        uses: sphinx-notes/pages@v3
        run: source $CONDA/etc/profile.d/conda.sh && conda activate multibody-book     

